<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Configurations>Debug;Release</Configurations>
    <Version>6.1.3</Version>
    <Product>Oqtane</Product>
    <Authors>Shaun Walker</Authors>
    <Company>.NET Foundation</Company>
    <Description>CMS and Application Framework for Blazor and .NET MAUI</Description>
    <Copyright>.NET Foundation</Copyright>
    <PackageProjectUrl>https://www.oqtane.org</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/oqtane/oqtane.framework/blob/dev/LICENSE</PackageLicenseUrl>
    <PackageReleaseNotes>https://github.com/oqtane/oqtane.framework/releases/tag/v6.1.3</PackageReleaseNotes>
    <RepositoryUrl>https://github.com/oqtane/oqtane.framework</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <RootNamespace>Teamx.Theme.practice.Client</RootNamespace>
    <IsPackable>true</IsPackable>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Themes\Oqtane.Theme.Corporate\.git\config" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\description" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\HEAD" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\applypatch-msg.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\commit-msg.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\fsmonitor-watchman.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\post-update.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\pre-applypatch.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\pre-commit.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\pre-merge-commit.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\pre-push.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\pre-rebase.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\pre-receive.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\prepare-commit-msg.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\push-to-checkout.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\sendemail-validate.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\hooks\update.sample" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\index" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\info\exclude" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\logs\HEAD" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\logs\refs\heads\main" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\logs\refs\remotes\origin\HEAD" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\objects\pack\pack-53b4359fc5fb8c65d301ddbea027c0339b41a217.idx" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\objects\pack\pack-53b4359fc5fb8c65d301ddbea027c0339b41a217.pack" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\objects\pack\pack-53b4359fc5fb8c65d301ddbea027c0339b41a217.rev" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\packed-refs" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\refs\heads\main" />
    <None Include="Themes\Oqtane.Theme.Corporate\.git\refs\remotes\origin\HEAD" />
    <None Include="Themes\Oqtane.Theme.Corporate\Client\Oqtane.Theme.Corporate.Client.csproj" />
    <None Include="Themes\Oqtane.Theme.Corporate\Oqtane.Theme.Corporate.sln" />
    <None Include="Themes\Oqtane.Theme.Corporate\Package\Oqtane.Theme.Corporate.Package.csproj" />
    <None Include="Themes\Teamx.Theme.practice\Client\Teamx.Theme.practice.Client.csproj" />
    <None Include="Themes\Teamx.Theme.practice\Package\Teamx.Theme.practice.Package.csproj" />
    <None Include="Themes\Teamx.Theme.practice\Teamx.Theme.practice.sln" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Oqtane.Shared\Oqtane.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Installer\Controls\AzureSqlConfig.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Themes\Oqtane.Theme.Corporate\.git\objects\info\" />
    <Folder Include="Themes\Oqtane.Theme.Corporate\.git\refs\tags\" />
  </ItemGroup>

  <PropertyGroup>
    <PublishTrimmed>false</PublishTrimmed>
    <BlazorEnableCompression>false</BlazorEnableCompression>
  </PropertyGroup>

</Project>
