<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Version>1.0.0</Version>
    <Authors>Teamx</Authors>
    <Company>Teamx</Company>
    <Description>[Description]</Description>
    <Product>Teamx.Theme.practice</Product>
    <Copyright>Teamx</Copyright>
    <AssemblyName>Teamx.Theme.practice.Client.Oqtane</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Oqtane.Client"><HintPath>..\..\oqtane\Oqtane.Server\bin\Debug\net9.0\Oqtane.Client.dll</HintPath></Reference>
    <Reference Include="Oqtane.Shared"><HintPath>..\..\oqtane\Oqtane.Server\bin\Debug\net9.0\Oqtane.Shared.dll</HintPath></Reference>
  </ItemGroup>

  <PropertyGroup>
    <!-- there may be other elements here -->
    <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
